import { TextLoading } from '@/componentes/TextLoading'
import Head from 'next/head'



export default function Home() {
  return (
    <>
      <Head>
        <title>Blurry Loading</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img src="https://images.unsplash.com/photo-1576161787924-01bb08dad4a4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2104&q=80" alt="" />
      <TextLoading/>
    </>
  )
}
